// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartEnergy.DeviceUsageAPI.Infrastructure;

namespace SmartEnergy.DeviceUsageAPI.Migrations
{
    [DbContext(typeof(DeviceUsageDbContext))]
    [Migration("20210727112457_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartEnergy.DeviceUsageAPI.DomainModel.DeviceUsage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int?>("IncidentID")
                        .HasColumnType("int");

                    b.Property<int?>("SafetyDocumentID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkPlanID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkRequestID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("DeviceUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
